# Generated by Django 4.0.1 on 2022-01-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputtedFile', models.FileField(default='textfiles.txt', upload_to='')),
                ('testField', models.CharField(max_length=250)),
            ],
        ),
    ]
