# Generated by Django 4.0.1 on 2022-01-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textFiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfiles',
            name='useremail',
        ),
    ]
