# Generated by Django 4.0.1 on 2022-01-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textFiles', '0002_remove_textfiles_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfiles',
            name='useremail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
