# Generated by Django 4.0.1 on 2022-01-30 06:47

from django.db import migrations, models
import textFiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('textFiles', '0003_textfiles_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfiles',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='textfiles',
            name='inputtedFile',
            field=models.FileField(blank=True, null=True, upload_to=textFiles.models.upload_path),
        ),
    ]
