# Generated by Django 4.0.1 on 2022-01-29 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textFiles', '0003_textfiles_inputtedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfiles',
            name='testField',
        ),
    ]
